### ISSUE TITLE
import mpl_toolkits.basemap as basemap fails on matplotlib

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/basemap-feedstock#31]
Issue: ImportError cannot import name 'is_scalar'

conda packages used

```
    basemap:              1.1.0-py35h50ae964_6                 conda-forge
    matplotlib:           3.0.0-py35h0b34cb6_1                 conda-forge
```

On Circle CI https://circleci.com/gh/conda-forge/mss-feedstock/178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
+ mss -h
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/mss", line 7, in <module>
    from mslib.msui.mss_pyui import main
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mss_pyui.py", line 49, in <module>
    from mslib.msui.mss_qt import ui_mainwindow as ui
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mss_qt.py", line 157, in <module>
    globals()[mod] = importlib.import_module("mslib.msui.qt5." + mod)
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/qt5/ui_sideview_window.py", line 64, in <module>
    from mslib.msui.mpl_qtwidget import MplSideViewWidget
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mpl_qtwidget.py", line 54, in <module>
    from mslib.msui import mpl_map
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mpl_map.py", line 48, in <module>
    import mpl_toolkits.basemap as basemap
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 17, in <module>
    from matplotlib.cbook import is_scalar, dedent
ImportError: cannot import name 'is_scalar'
Tests failed for mss-1.7.3-py35_2.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for mss-1.7.3-py35_2.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: mss-1.7.3-py35_2.tar.bz2
Exited with code 1


```

see also https://github.com/matplotlib/basemap/issues/424

**Comment by ReimarBauer** [comment]
this was fixed, we need a new build
https://github.com/matplotlib/basemap/pull/398

**Comment by ReimarBauer** [comment]
@ocefpaf can you please rebuild this with the fix in place, Thx

**Comment by zkurtz** [comment]
Related? After a seemingly-successful `conda install basemap`:

```
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpl_toolkits.basemap as basemap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
```

**Comment by fongangbatuo** [comment]
i get this Error when i try importing Basemap(how may i correct the installation?)---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-d9467465a3b6> in <module>()
----> 1 from mpl_toolkits.basemap import Basemap

~\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py in <module>()
    153
    154 # create dictionary that maps epsg codes to Basemap kwargs.
--> 155 pyproj_datadir = os.environ['PROJ_LIB']
    156 epsgf = open(os.path.join(pyproj_datadir,'epsg'))
    157 epsg_dict={}

~\Anaconda3\lib\os.py in __getitem__(self, key)
    676         except KeyError:
    677             # raise KeyError with the original key value
--> 678             raise KeyError(key) from None
    679         return self.decodevalue(value)
    680

KeyError: 'PROJ_LIB'

**Comment by ocefpaf** [comment]
@fongangbatuo please open a new issue with the information requested from the "new issue template." It is virtually impossible to help you debug this based on an old discussion that is already solved.
