### ISSUE TITLE
basemap crashes when using most recent matplotlib 3.3.0

### ISSUE THREAD

**Issue by joernu76** [conda-forge/basemap-feedstock#64]
To replicate, install fresh packages in conda

```
conda create -n basemap-test -c conda-forge basemap matplotlib
```

all packages:

```
 (e) basemap-test  ~  conda list                                     
# packages in environment at /home/icg173/anaconda3/envs/basemap-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
basemap                   1.2.1            py37hd1be537_2    conda-forge
blas                      2.17                   openblas    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
geos                      3.8.0                he1b5a44_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
intel-openmp              2019.4                      243  
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_13    conda-forge
libgfortran-ng            7.5.0               hdf63c60_13    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_13    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.1               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py37hd478181_1    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py37h516909a_0    conda-forge
mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nspr                      4.27                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.19.1           py37h8960a57_0    conda-forge
numpy-base                1.18.5           py37h2f8d375_0  
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.2                       py_0    conda-forge
proj4                     5.2.0             he1b5a44_1006    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    1.9.6           py37h516909a_1002    conda-forge
pyqt                      5.12.3           py37h8685d9f_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyshp                     2.1.0                      py_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.2.1           py37hc8dfbb8_0    conda-forge
sip                       4.19.23          py37h3340039_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

```
 (e) basemap-test2  ~  src  basemap  conda info                                                                                                                                issue496 

     active environment : basemap-test2
    active env location : /home/icg173/anaconda3/envs/basemap-test2
            shell level : 2
       user config file : /home/icg173/.condarc
 populated config files : /home/icg173/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /home/icg173/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/icg173/anaconda3/pkgs
                          /home/icg173/.conda/pkgs
       envs directories : /home/icg173/anaconda3/envs
                          /home/icg173/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.19.0-9-amd64 debian/10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

to cause the error:

```
 (e) basemap-test  ~  python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpl_toolkits.basemap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/icg173/anaconda3/envs/basemap-test/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 50, in <module>
    from .proj import Proj
  File "/home/icg173/anaconda3/envs/basemap-test/lib/python3.7/site-packages/mpl_toolkits/basemap/proj.py", line 6, in <module>
    from matplotlib.cbook import dedent
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/home/icg173/anaconda3/envs/basemap-test/lib/python3.7/site-packages/matplotlib/cbook/__init__.py)
```

See
https://github.com/matplotlib/basemap/issues/495
and
https://bitbucket.org/wxmetvis/mss/issues/574/matplotlib-cannot-be-upgraded-due-to-error

I provided a fix that has been merged into basemap. But I need this in conda-forge.

Can we make a new release here? I could try providing a merge request for this.

**Comment by ocefpaf** [comment]
Was there a new baseman release after that PR? If so the bot will probably update this automatically. If not, ask for a  release upstream. If the release will take a while we can add a backport patch.

**Comment by joernu76** [comment]
Nope. Currently conda/basemap seems to me to be ahead. githup basemap is on 1.2.2 and this seems to be 1.3.0?

**Comment by ocefpaf** [comment]
Yeah, the lack of releases is forcing our hands :-(
Let's ask for an official release first. Building from a commit, even for a deprecated package like basemap, is not really a good thing.

**Comment by joernu76** [comment]
So, which version should be released upstream? matplotlib is deprecated, which justifies only a minor increment to 1.2.2; how would that be handled here?

**Comment by ocefpaf** [comment]
> how would that be handled here?

I guess that there are more changes than just this one. The version here reflects that. Ideally they would release something with all those changes.

**Comment by ReimarBauer** [comment]
@ocefpaf there was a new release 1.2.2, the bot seems not get triggered. The recipe patch is based on v1.2.1

https://github.com/matplotlib/basemap/releases/tag/v1.2.2rel

An other option for our project would be to add @joernu76 patch to our build process. That's also not a wanted solution.

**Comment by dopplershift** [comment]
Things are kind of a mess since the decision was made to put this repo on version "1.3"...then upstream released 1.2.2, which is "older" than the version here.

**Comment by ocefpaf** [comment]
Yep. I did consult with upstream to do that though. The only option is to remove the 1.3 and build the new one. People will need to clean their cache.

I'll check this on Monday. Still recovering from a full week of zoom.

**Comment by dopplershift** [comment]
*sigh* Alright then.

**Comment by ocefpaf** [comment]
> _sigh_ Alright then.

If you have a better idea please let me know. I won't ask for a proper release upstream though, they are not interested in maintaining basemap and issuing proper releases.

**Comment by dopplershift** [comment]
No, I don't, which is part of the frustration. And that's not with your efforts or anything, just at the whole mess.

**Comment by dopplershift** [comment]
To be clear, 1.2.2 is a proper release from upstream, 11 days ago. The "final" release.

**Comment by ocefpaf** [comment]
> No, I don't, which is part of the frustration. And that's not with your efforts or anything, just at the whole mess.

OK. Moving ahead with that plan then...

**Comment by ocefpaf** [comment]
Actually, moving then to broken would be quite disruptive. I'm moving then to a dev channel where they should've been from the start. People kept demanding the latest version on the main channel due to the lack of releases and now we are in this mess. So let's clean it up without more grief.

**Comment by ocefpaf** [comment]
> To be clear, 1.2.2 is a proper release from upstream, 11 days ago. The "final" release.

I sure hope that gets people moving to cartopy. I'm afraid there will be a new maintainer willing to take on basemap just because their code base still relies on it.
